name: Docker

on:
    push:
        branches:
            - github-ci

jobs:
    build-push:
        name: Build Docker images and push them
        runs-on: node:14-alpine
        steps:
            - name: Checkout default branch
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push latest
              id: docker-latest
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: garnetlabs/garnet-oss:latest

            - name: Build and push dev
              id: docker-dev
              uses: docker/build-push-action@v2
              with:
                  file: dev.Dockerfile
                  push: true
                  tags: garnet/garnet-oss:dev

            - name: Image digests
              run: |
                  echo "Pushed latest: ${{ steps.docker-latest.outputs.digest }}"
                  echo "Pushed dev: ${{ steps.docker-dev.outputs.digest }}"